// Generated by Aifei Generator. DO NOT EDIT.

package loginlog

import (
	"github.com/crazy-airhead/aifei-go/db"
	"reflect"
	"time"
)

var TableLoginLog = &db.Table{
	Name:             "sys_login_log",
	Fields:           "id,user_id,login_time,ip",
	PrimaryKeys:      []string{"id"},
	GeneratedColumns: []string{},
	FieldTypes: map[string]reflect.Type{
		"id":         reflect.TypeOf(int(0)),
		"user_id":    reflect.TypeOf(int(0)),
		"login_time": reflect.TypeOf(time.Time{}),
		"ip":         reflect.TypeOf(""),
	},
}

type BaseLoginLog struct {
	*db.Row
}

func NewBaseLoginLog() *BaseLoginLog {
	return &BaseLoginLog{Row: db.NewRow(TableLoginLog.Name)}
}

// NewLoginLogWithRow wraps a queried *db.Row as a BaseLoginLog. Unlike a bare
// struct literal it runs initLoginLogRow, so the result carries table name,
// primary keys and decoded JSON columns — Update()/Delete() work on it.
func NewLoginLogWithRow(row *db.Row) *BaseLoginLog {
	return &BaseLoginLog{Row: initLoginLogRow(row)}
}

func (r *BaseLoginLog) Id() int {
	return r.GetInt("id")
}

func (r *BaseLoginLog) UserId() int {
	return r.GetInt("user_id")
}

func (r *BaseLoginLog) LoginTime() time.Time {
	return r.GetTime("login_time")
}

func (r *BaseLoginLog) Ip() string {
	return r.GetStr("ip")
}

func (r *BaseLoginLog) SetId(v int) *BaseLoginLog {
	r.Set("id", v)
	return r
}

func (r *BaseLoginLog) SetUserId(v int) *BaseLoginLog {
	r.Set("user_id", v)
	return r
}

func (r *BaseLoginLog) SetLoginTime(v time.Time) *BaseLoginLog {
	r.Set("login_time", v)
	return r
}

func (r *BaseLoginLog) SetIp(v string) *BaseLoginLog {
	r.Set("ip", v)
	return r
}

func (r *BaseLoginLog) Id_(v int) *BaseLoginLog {
	return r.SetId(v)
}

func (r *BaseLoginLog) UserId_(v int) *BaseLoginLog {
	return r.SetUserId(v)
}

func (r *BaseLoginLog) LoginTime_(v time.Time) *BaseLoginLog {
	return r.SetLoginTime(v)
}

func (r *BaseLoginLog) Ip_(v string) *BaseLoginLog {
	return r.SetIp(v)
}

func (r *BaseLoginLog) Insert() (*BaseLoginLog, error) {
	_, err := r.Row.Insert()
	return r, err
}

func (r *BaseLoginLog) Update() (bool, error) {
	return r.Row.Update()
}

func (r *BaseLoginLog) Delete() (bool, error) {
	return r.Row.Delete()
}

func initLoginLogRow(row *db.Row) *db.Row {
	return db.DecodeJSONFields(row.SetTable(TableLoginLog.Name).SetPrimaryKeys(TableLoginLog.PrimaryKeys...))
}

// LoginLogFromRow wraps a raw-SQL *db.Row as a typed *LoginLog (nil-safe).
// It lives in base.go — which re-generation always overwrites — so existing
// projects pick it up by re-running the generator; referencing the model type
// from here is fine within one package.
func LoginLogFromRow(row *db.Row) *LoginLog {
	if row == nil {
		return nil
	}
	return &LoginLog{BaseLoginLog: NewLoginLogWithRow(row)}
}

// LoginLogFromRows wraps a slice of raw-SQL rows as typed *LoginLog values.
func LoginLogFromRows(rows []*db.Row) []*LoginLog {
	out := make([]*LoginLog, len(rows))
	for i, row := range rows {
		out[i] = LoginLogFromRow(row)
	}
	return out
}

func (b *BaseLoginLog) InitRow(row *db.Row) {
	b.Row = initLoginLogRow(row)
}

func init() {
	db.RegisterTable(TableLoginLog)
}
