// Generated by Aifei Generator.
// This file is NOT overwritten on re-generation. Add custom queries here.

package loginlog

import (
	"github.com/crazy-airhead/aifei-go/db"
)

// LoginLogDao is a typed query builder for LoginLog (table "sys_login_log").
// Chain a Sql/Select/RawSql setup method (they return *LoginLogDao), then call a
// terminal method (Find/FindFirst/Paginate/Count/...) which returns typed
// results. The table is already bound, so unlike db.Dao no table name is
// passed on every call. Create a fresh one per query via NewLoginLogDao().
type LoginLogDao struct {
	*db.Dao
}

// NewLoginLogDao returns a fresh typed Dao bound to the default db config.
func NewLoginLogDao() *LoginLogDao {
	return &LoginLogDao{Dao: db.Use()}
}

// Sql sets an Enjoy SQL template and its named parameters.
func (d *LoginLogDao) Sql(sqlStr string, data map[string]interface{}) *LoginLogDao {
	d.Dao.Sql(sqlStr, data)
	return d
}

// SqlWithArgs sets an Enjoy SQL template with positional arguments.
func (d *LoginLogDao) SqlWithArgs(sqlStr string, args ...interface{}) *LoginLogDao {
	d.Dao.SqlWithArgs(sqlStr, args...)
	return d
}

// SqlById sets a cached Enjoy SQL template (by id) and its named parameters.
func (d *LoginLogDao) SqlById(sqlID string, data map[string]interface{}) *LoginLogDao {
	d.Dao.SqlById(sqlID, data)
	return d
}

// SqlByIdWithArgs sets a cached Enjoy SQL template (by id) with positional arguments.
func (d *LoginLogDao) SqlByIdWithArgs(sqlID string, args ...interface{}) *LoginLogDao {
	d.Dao.SqlByIdWithArgs(sqlID, args...)
	return d
}

// RawSql sets a raw SQL string with positional arguments.
func (d *LoginLogDao) RawSql(query string, args ...interface{}) *LoginLogDao {
	d.Dao.RawSql(query, args...)
	return d
}

// Select restricts the selected columns.
func (d *LoginLogDao) Select(fields string) *LoginLogDao {
	d.Dao.Select(fields)
	return d
}

// Find executes the query and returns all matching rows as typed models.
func (d *LoginLogDao) Find() ([]*LoginLog, error) {
	rows, err := d.Dao.Find()
	if err != nil {
		return nil, err
	}
	return LoginLogFromRows(rows), nil
}

// FindFirst executes the query and returns the first matching row as a typed model.
func (d *LoginLogDao) FindFirst() (*LoginLog, error) {
	row, err := d.Dao.FindFirst()
	if err != nil {
		return nil, err
	}
	return LoginLogFromRow(row), nil
}

// FindOne executes the query and returns the single matching row as a typed model.
func (d *LoginLogDao) FindOne() (*LoginLog, error) {
	row, err := d.Dao.FindOne()
	if err != nil {
		return nil, err
	}
	return LoginLogFromRow(row), nil
}

// FindExists reports whether the query matches any row.
func (d *LoginLogDao) FindExists() (bool, error) {
	return d.Dao.FindExists()
}

// LoginLogPage is db.Page with typed rows: the wire format (json tags) is
// identical, but Rows carries *LoginLog instead of *db.Row.
type LoginLogPage struct {
	PageNum    int         `json:"pageNum"`
	PageSize   int         `json:"pageSize"`
	TotalRows  int64       `json:"totalRows"`
	TotalPages int         `json:"totalPages"`
	Rows       []*LoginLog `json:"rows"`
}

// Paginate executes the query and returns a page of typed rows.
func (d *LoginLogDao) Paginate(pageNum, pageSize int) (*LoginLogPage, error) {
	page, err := d.Dao.Paginate(pageNum, pageSize)
	if err != nil {
		return nil, err
	}
	return &LoginLogPage{
		PageNum:    page.PageNum,
		PageSize:   page.PageSize,
		TotalRows:  page.TotalRows,
		TotalPages: page.TotalPages,
		Rows:       LoginLogFromRows(page.Rows),
	}, nil
}

// FindBy queries by a where clause or a single field with arguments.
func (d *LoginLogDao) FindBy(whereOrField string, args ...interface{}) ([]*LoginLog, error) {
	rows, err := d.Dao.FindBy(TableLoginLog.Name, whereOrField, args...)
	if err != nil {
		return nil, err
	}
	return LoginLogFromRows(rows), nil
}

// FindFirstBy queries the first row by a where clause or a single field with arguments.
func (d *LoginLogDao) FindFirstBy(whereOrField string, args ...interface{}) (*LoginLog, error) {
	row, err := d.Dao.FindFirstBy(TableLoginLog.Name, whereOrField, args...)
	if err != nil {
		return nil, err
	}
	return LoginLogFromRow(row), nil
}

// FindIn loads rows where field matches any of values (a typed IN query),
// e.g. FindIn("user_id", 1, 2, 3).
func (d *LoginLogDao) FindIn(field string, values ...interface{}) ([]*LoginLog, error) {
	rows, err := d.Dao.FindIn(TableLoginLog.Name, field, values...)
	if err != nil {
		return nil, err
	}
	return LoginLogFromRows(rows), nil
}

// FindByID loads a single row by its primary key.
func (d *LoginLogDao) FindByID(id int) (*LoginLog, error) {
	row, err := d.Dao.FindByID(TableLoginLog.Name, id)
	if err != nil {
		return nil, err
	}
	return LoginLogFromRow(row), nil
}

// DeleteByID deletes a single row by its primary key.
func (d *LoginLogDao) DeleteByID(id int) (bool, error) {
	return d.Dao.DeleteByID(TableLoginLog.Name, id)
}

// FindByIds loads rows matching any of the given primary keys (WHERE pk IN ...).
func (d *LoginLogDao) FindByIds(ids ...int) ([]*LoginLog, error) {
	vals := make([]interface{}, len(ids))
	for i, id := range ids {
		vals[i] = id
	}
	rows, err := d.Dao.FindIn(TableLoginLog.Name, "id", vals...)
	if err != nil {
		return nil, err
	}
	return LoginLogFromRows(rows), nil
}

// DeleteByIds deletes rows matching any of the given primary keys (WHERE pk IN ...).
func (d *LoginLogDao) DeleteByIds(ids ...int) (int64, error) {
	vals := make([]interface{}, len(ids))
	for i, id := range ids {
		vals[i] = id
	}
	return d.Dao.DeleteInIds(TableLoginLog.Name, vals...)
}

// Count returns the total number of rows.
func (d *LoginLogDao) Count() (int64, error) {
	return d.Dao.Count(TableLoginLog.Name)
}

// CountBy counts rows matching a where clause or a single field with arguments.
func (d *LoginLogDao) CountBy(whereOrField string, args ...interface{}) (int64, error) {
	return d.Dao.CountBy(TableLoginLog.Name, whereOrField, args...)
}

// DeleteBy deletes rows matching a where clause or a single field with arguments.
func (d *LoginLogDao) DeleteBy(whereOrField string, args ...interface{}) (int64, error) {
	return d.Dao.DeleteBy(TableLoginLog.Name, whereOrField, args...)
}

// LoginLogFindById loads a single row by its primary key.
func LoginLogFindById(id int) (*LoginLog, error) {
	return NewLoginLogDao().FindByID(id)
}

// LoginLogDeleteById deletes a single row by its primary key.
func LoginLogDeleteById(id int) (bool, error) {
	return NewLoginLogDao().DeleteByID(id)
}

// LoginLogFindByIds loads rows matching any of the given primary keys.
func LoginLogFindByIds(ids ...int) ([]*LoginLog, error) {
	return NewLoginLogDao().FindByIds(ids...)
}

// LoginLogDeleteByIds deletes rows matching any of the given primary keys.
func LoginLogDeleteByIds(ids ...int) (int64, error) {
	return NewLoginLogDao().DeleteByIds(ids...)
}

// LoginLogFindBy queries by a where clause or a single field with arguments.
func LoginLogFindBy(whereOrField string, args ...interface{}) ([]*LoginLog, error) {
	return NewLoginLogDao().FindBy(whereOrField, args...)
}

// LoginLogFindFirstBy queries the first row by a where clause or a single field with arguments.
func LoginLogFindFirstBy(whereOrField string, args ...interface{}) (*LoginLog, error) {
	return NewLoginLogDao().FindFirstBy(whereOrField, args...)
}

// LoginLogDeleteBy deletes rows matching a where clause or a single field with arguments.
func LoginLogDeleteBy(whereOrField string, args ...interface{}) (int64, error) {
	return NewLoginLogDao().DeleteBy(whereOrField, args...)
}

// LoginLogCount returns the total number of rows.
func LoginLogCount() (int64, error) {
	return NewLoginLogDao().Count()
}

// LoginLogCountBy counts rows matching a where clause or a single field with arguments.
func LoginLogCountBy(whereOrField string, args ...interface{}) (int64, error) {
	return NewLoginLogDao().CountBy(whereOrField, args...)
}
