// Generated by Aifei Generator.
// This file is NOT overwritten on re-generation. Add custom queries here.

package loginlog

import (
	"github.com/crazy-airhead/aifei-go/aifei"
	"github.com/crazy-airhead/aifei-go/server"
	"strconv"
)

const (
	LoginLogServicePrefix = "/loginLog"

	// loginLogListSql is the Enjoy SQL template for List and Paginate.
	// Query params are matched via the where/and directives in queryConditions.
	loginLogListSql = `SELECT * FROM sys_login_log
#where(user_id, '=', user_id)
#and(login_time, '=', login_time)
#and(ip, '=', ip)
ORDER BY id DESC`
)

func init() {
	server.RegisterService(LoginLogServicePrefix, &LoginLogService{})
}

type LoginLogService struct{}

// List returns records matching query params (no pagination).
func (s *LoginLogService) List(in aifei.Input) aifei.Output {
	filter := in.GetMap()
	rows, err := NewLoginLogDao().Sql(loginLogListSql, filter).Find()
	if err != nil {
		return server.Fail(err.Error())
	}
	return server.Of(rows)
}

// Paginate returns paginated records matching query params.
func (s *LoginLogService) Paginate(in aifei.Input) aifei.Output {
	pageNum := in.GetInt("page", 1)
	pageSize := in.GetInt("size", 10)
	filter := in.GetMap()
	page, err := NewLoginLogDao().Sql(loginLogListSql, filter).Paginate(pageNum, pageSize)
	if err != nil {
		return server.Fail(err.Error())
	}
	return server.Of(page)
}

// Create inserts a new record.
func (s *LoginLogService) Create(in aifei.Input) aifei.Output {
	u := NewLoginLog()
	if err := in.GetBean(u); err != nil {
		return server.Fail("invalid request: " + err.Error())
	}
	result, err := u.Insert()
	if err != nil {
		return server.Fail(err.Error())
	}
	return server.Of(result.GetID())
}

// GetById retrieves a record by primary key.
func (s *LoginLogService) GetById(in aifei.Input) aifei.Output {
	id, err := strconv.Atoi(in.Param("id"))
	if err != nil {
		return server.Fail("invalid id")
	}
	u, err := LoginLogFindById(id)
	if err != nil {
		return server.Fail(err.Error())
	}
	if u == nil {
		return server.Fail("LoginLog not found")
	}
	return server.Of(u)
}

// UpdateById updates a record by primary key.
func (s *LoginLogService) UpdateById(in aifei.Input) aifei.Output {
	id, err := strconv.Atoi(in.Param("id"))
	if err != nil {
		return server.Fail("invalid id")
	}
	existing, err := LoginLogFindById(id)
	if err != nil || existing == nil {
		return server.Fail("LoginLog not found")
	}
	if err := in.GetBean(existing); err != nil {
		return server.Fail("invalid request: " + err.Error())
	}
	if _, err := existing.Update(); err != nil {
		return server.Fail(err.Error())
	}
	return server.Of(id)
}

// DeleteById deletes a record by primary key.
func (s *LoginLogService) DeleteById(in aifei.Input) aifei.Output {
	id, err := strconv.Atoi(in.Param("id"))
	if err != nil {
		return server.Fail("invalid id")
	}
	if _, err := LoginLogDeleteById(id); err != nil {
		return server.Fail(err.Error())
	}
	return server.Of(nil)
}
