// Generated by Aifei Generator. DO NOT EDIT.

package user

import (
	"github.com/crazy-airhead/aifei-go/db"
	"reflect"
	"time"
)

var TableUser = &db.Table{
	Name:             "user",
	Fields:           "id,name,age,email,created_at",
	PrimaryKeys:      []string{"id"},
	GeneratedColumns: []string{},
	FieldTypes: map[string]reflect.Type{
		"id":         reflect.TypeOf(int(0)),
		"name":       reflect.TypeOf(""),
		"age":        reflect.TypeOf(int(0)),
		"email":      reflect.TypeOf(""),
		"created_at": reflect.TypeOf(time.Time{}),
	},
}

type BaseUser struct {
	*db.Row
}

func NewBaseUser() *BaseUser {
	return &BaseUser{Row: db.NewRow(TableUser.Name)}
}

// NewUserWithRow wraps a queried *db.Row as a BaseUser. Unlike a bare
// struct literal it runs initUserRow, so the result carries table name,
// primary keys and decoded JSON columns — Update()/Delete() work on it.
func NewUserWithRow(row *db.Row) *BaseUser {
	return &BaseUser{Row: initUserRow(row)}
}

func (r *BaseUser) Id() int {
	return r.GetInt("id")
}

func (r *BaseUser) Name() string {
	return r.GetStr("name")
}

func (r *BaseUser) Age() int {
	return r.GetInt("age")
}

func (r *BaseUser) Email() string {
	return r.GetStr("email")
}

func (r *BaseUser) CreatedAt() time.Time {
	return r.GetTime("created_at")
}

func (r *BaseUser) SetId(v int) *BaseUser {
	r.Set("id", v)
	return r
}

func (r *BaseUser) SetName(v string) *BaseUser {
	r.Set("name", v)
	return r
}

func (r *BaseUser) SetAge(v int) *BaseUser {
	r.Set("age", v)
	return r
}

func (r *BaseUser) SetEmail(v string) *BaseUser {
	r.Set("email", v)
	return r
}

func (r *BaseUser) SetCreatedAt(v time.Time) *BaseUser {
	r.Set("created_at", v)
	return r
}

func (r *BaseUser) Id_(v int) *BaseUser {
	return r.SetId(v)
}

func (r *BaseUser) Name_(v string) *BaseUser {
	return r.SetName(v)
}

func (r *BaseUser) Age_(v int) *BaseUser {
	return r.SetAge(v)
}

func (r *BaseUser) Email_(v string) *BaseUser {
	return r.SetEmail(v)
}

func (r *BaseUser) CreatedAt_(v time.Time) *BaseUser {
	return r.SetCreatedAt(v)
}

func (r *BaseUser) Insert() (*BaseUser, error) {
	_, err := r.Row.Insert()
	return r, err
}

func (r *BaseUser) Update() (bool, error) {
	return r.Row.Update()
}

func (r *BaseUser) Delete() (bool, error) {
	return r.Row.Delete()
}

func initUserRow(row *db.Row) *db.Row {
	return db.DecodeJSONFields(row.SetTable(TableUser.Name).SetPrimaryKeys(TableUser.PrimaryKeys...))
}

// UserFromRow wraps a raw-SQL *db.Row as a typed *User (nil-safe).
// It lives in base.go — which re-generation always overwrites — so existing
// projects pick it up by re-running the generator; referencing the model type
// from here is fine within one package.
func UserFromRow(row *db.Row) *User {
	if row == nil {
		return nil
	}
	return &User{BaseUser: NewUserWithRow(row)}
}

// UserFromRows wraps a slice of raw-SQL rows as typed *User values.
func UserFromRows(rows []*db.Row) []*User {
	out := make([]*User, len(rows))
	for i, row := range rows {
		out[i] = UserFromRow(row)
	}
	return out
}

func (b *BaseUser) InitRow(row *db.Row) {
	b.Row = initUserRow(row)
}

func init() {
	db.RegisterTable(TableUser)
}
