// Generated by Aifei Generator.
// This file is NOT overwritten on re-generation. Add custom queries here.

package user

import (
	"github.com/crazy-airhead/aifei-go/db"
)

// UserDao is a typed query builder for User (table "user").
// Chain a Sql/Select/RawSql setup method (they return *UserDao), then call a
// terminal method (Find/FindFirst/Paginate/Count/...) which returns typed
// results. The table is already bound, so unlike db.Dao no table name is
// passed on every call. Create a fresh one per query via NewUserDao().
type UserDao struct {
	*db.Dao
}

// NewUserDao returns a fresh typed Dao bound to the default db config.
func NewUserDao() *UserDao {
	return &UserDao{Dao: db.Use()}
}

// Sql sets an Enjoy SQL template and its named parameters.
func (d *UserDao) Sql(sqlStr string, data map[string]interface{}) *UserDao {
	d.Dao.Sql(sqlStr, data)
	return d
}

// SqlWithArgs sets an Enjoy SQL template with positional arguments.
func (d *UserDao) SqlWithArgs(sqlStr string, args ...interface{}) *UserDao {
	d.Dao.SqlWithArgs(sqlStr, args...)
	return d
}

// SqlById sets a cached Enjoy SQL template (by id) and its named parameters.
func (d *UserDao) SqlById(sqlID string, data map[string]interface{}) *UserDao {
	d.Dao.SqlById(sqlID, data)
	return d
}

// SqlByIdWithArgs sets a cached Enjoy SQL template (by id) with positional arguments.
func (d *UserDao) SqlByIdWithArgs(sqlID string, args ...interface{}) *UserDao {
	d.Dao.SqlByIdWithArgs(sqlID, args...)
	return d
}

// RawSql sets a raw SQL string with positional arguments.
func (d *UserDao) RawSql(query string, args ...interface{}) *UserDao {
	d.Dao.RawSql(query, args...)
	return d
}

// Select restricts the selected columns.
func (d *UserDao) Select(fields string) *UserDao {
	d.Dao.Select(fields)
	return d
}

// Find executes the query and returns all matching rows as typed models.
func (d *UserDao) Find() ([]*User, error) {
	rows, err := d.Dao.Find()
	if err != nil {
		return nil, err
	}
	return UserFromRows(rows), nil
}

// FindFirst executes the query and returns the first matching row as a typed model.
func (d *UserDao) FindFirst() (*User, error) {
	row, err := d.Dao.FindFirst()
	if err != nil {
		return nil, err
	}
	return UserFromRow(row), nil
}

// FindOne executes the query and returns the single matching row as a typed model.
func (d *UserDao) FindOne() (*User, error) {
	row, err := d.Dao.FindOne()
	if err != nil {
		return nil, err
	}
	return UserFromRow(row), nil
}

// FindExists reports whether the query matches any row.
func (d *UserDao) FindExists() (bool, error) {
	return d.Dao.FindExists()
}

// UserPage is db.Page with typed rows: the wire format (json tags) is
// identical, but Rows carries *User instead of *db.Row.
type UserPage struct {
	PageNum    int     `json:"pageNum"`
	PageSize   int     `json:"pageSize"`
	TotalRows  int64   `json:"totalRows"`
	TotalPages int     `json:"totalPages"`
	Rows       []*User `json:"rows"`
}

// Paginate executes the query and returns a page of typed rows.
func (d *UserDao) Paginate(pageNum, pageSize int) (*UserPage, error) {
	page, err := d.Dao.Paginate(pageNum, pageSize)
	if err != nil {
		return nil, err
	}
	return &UserPage{
		PageNum:    page.PageNum,
		PageSize:   page.PageSize,
		TotalRows:  page.TotalRows,
		TotalPages: page.TotalPages,
		Rows:       UserFromRows(page.Rows),
	}, nil
}

// FindBy queries by a where clause or a single field with arguments.
func (d *UserDao) FindBy(whereOrField string, args ...interface{}) ([]*User, error) {
	rows, err := d.Dao.FindBy(TableUser.Name, whereOrField, args...)
	if err != nil {
		return nil, err
	}
	return UserFromRows(rows), nil
}

// FindFirstBy queries the first row by a where clause or a single field with arguments.
func (d *UserDao) FindFirstBy(whereOrField string, args ...interface{}) (*User, error) {
	row, err := d.Dao.FindFirstBy(TableUser.Name, whereOrField, args...)
	if err != nil {
		return nil, err
	}
	return UserFromRow(row), nil
}

// FindIn loads rows where field matches any of values (a typed IN query),
// e.g. FindIn("user_id", 1, 2, 3).
func (d *UserDao) FindIn(field string, values ...interface{}) ([]*User, error) {
	rows, err := d.Dao.FindIn(TableUser.Name, field, values...)
	if err != nil {
		return nil, err
	}
	return UserFromRows(rows), nil
}

// FindByID loads a single row by its primary key.
func (d *UserDao) FindByID(id int) (*User, error) {
	row, err := d.Dao.FindByID(TableUser.Name, id)
	if err != nil {
		return nil, err
	}
	return UserFromRow(row), nil
}

// DeleteByID deletes a single row by its primary key.
func (d *UserDao) DeleteByID(id int) (bool, error) {
	return d.Dao.DeleteByID(TableUser.Name, id)
}

// FindByIds loads rows matching any of the given primary keys (WHERE pk IN ...).
func (d *UserDao) FindByIds(ids ...int) ([]*User, error) {
	vals := make([]interface{}, len(ids))
	for i, id := range ids {
		vals[i] = id
	}
	rows, err := d.Dao.FindIn(TableUser.Name, "id", vals...)
	if err != nil {
		return nil, err
	}
	return UserFromRows(rows), nil
}

// DeleteByIds deletes rows matching any of the given primary keys (WHERE pk IN ...).
func (d *UserDao) DeleteByIds(ids ...int) (int64, error) {
	vals := make([]interface{}, len(ids))
	for i, id := range ids {
		vals[i] = id
	}
	return d.Dao.DeleteInIds(TableUser.Name, vals...)
}

// Count returns the total number of rows.
func (d *UserDao) Count() (int64, error) {
	return d.Dao.Count(TableUser.Name)
}

// CountBy counts rows matching a where clause or a single field with arguments.
func (d *UserDao) CountBy(whereOrField string, args ...interface{}) (int64, error) {
	return d.Dao.CountBy(TableUser.Name, whereOrField, args...)
}

// DeleteBy deletes rows matching a where clause or a single field with arguments.
func (d *UserDao) DeleteBy(whereOrField string, args ...interface{}) (int64, error) {
	return d.Dao.DeleteBy(TableUser.Name, whereOrField, args...)
}

// UserFindById loads a single row by its primary key.
func UserFindById(id int) (*User, error) {
	return NewUserDao().FindByID(id)
}

// UserDeleteById deletes a single row by its primary key.
func UserDeleteById(id int) (bool, error) {
	return NewUserDao().DeleteByID(id)
}

// UserFindByIds loads rows matching any of the given primary keys.
func UserFindByIds(ids ...int) ([]*User, error) {
	return NewUserDao().FindByIds(ids...)
}

// UserDeleteByIds deletes rows matching any of the given primary keys.
func UserDeleteByIds(ids ...int) (int64, error) {
	return NewUserDao().DeleteByIds(ids...)
}

// UserFindBy queries by a where clause or a single field with arguments.
func UserFindBy(whereOrField string, args ...interface{}) ([]*User, error) {
	return NewUserDao().FindBy(whereOrField, args...)
}

// UserFindFirstBy queries the first row by a where clause or a single field with arguments.
func UserFindFirstBy(whereOrField string, args ...interface{}) (*User, error) {
	return NewUserDao().FindFirstBy(whereOrField, args...)
}

// UserDeleteBy deletes rows matching a where clause or a single field with arguments.
func UserDeleteBy(whereOrField string, args ...interface{}) (int64, error) {
	return NewUserDao().DeleteBy(whereOrField, args...)
}

// UserCount returns the total number of rows.
func UserCount() (int64, error) {
	return NewUserDao().Count()
}

// UserCountBy counts rows matching a where clause or a single field with arguments.
func UserCountBy(whereOrField string, args ...interface{}) (int64, error) {
	return NewUserDao().CountBy(whereOrField, args...)
}
