// Generated by Aifei Generator.
// This file is NOT overwritten on re-generation. Add custom logic here.

package user

// User is the data model for the user table.
type User struct {
	*BaseUser
}

// NewUser creates a new User ready for use with GetBean and Insert.
func NewUser() *User {
	return &User{BaseUser: NewBaseUser()}
}
