// Generated by Aifei Generator.
// This file is NOT overwritten on re-generation. Add custom logic here.

package user

// User is the data model for the user table.
type User struct {
	*BaseUser
}

// New creates a new User ready for use with GetBean and Insert.
func New() *User {
	return &User{BaseUser: NewBase()}
}
