// Generated by Aifei Generator.
// This file is NOT overwritten on re-generation. Add custom queries here.

package user

import (
	"github.com/crazy-airhead/aifei-go/aifei"
	"github.com/crazy-airhead/aifei-go/server"
	"strconv"
)

const (
	UserServicePrefix = "/user"

	// userListSql is the Enjoy SQL template for List and Paginate.
	// Query params are matched via the where/and directives in queryConditions.
	userListSql = `SELECT * FROM user
#where(name, '=', name)
#and(age, '=', age)
#and(email, '=', email)
#and(created_at, '=', created_at)
ORDER BY id DESC`
)

func init() {
	server.RegisterService(UserServicePrefix, &UserService{})
}

type UserService struct{}

// List returns records matching query params (no pagination).
func (s *UserService) List(in aifei.Input) aifei.Output {
	filter := in.GetMap()
	rows, err := NewUserDao().Sql(userListSql, filter).Find()
	if err != nil {
		return server.Fail(err.Error())
	}
	return server.Of(rows)
}

// Paginate returns paginated records matching query params.
func (s *UserService) Paginate(in aifei.Input) aifei.Output {
	pageNum := in.GetInt("page", 1)
	pageSize := in.GetInt("size", 10)
	filter := in.GetMap()
	page, err := NewUserDao().Sql(userListSql, filter).Paginate(pageNum, pageSize)
	if err != nil {
		return server.Fail(err.Error())
	}
	return server.Of(page)
}

// Create inserts a new record.
func (s *UserService) Create(in aifei.Input) aifei.Output {
	u := NewUser()
	if err := in.GetBean(u); err != nil {
		return server.Fail("invalid request: " + err.Error())
	}
	result, err := u.Insert()
	if err != nil {
		return server.Fail(err.Error())
	}
	return server.Of(result.GetID())
}

// GetById retrieves a record by primary key.
func (s *UserService) GetById(in aifei.Input) aifei.Output {
	id, err := strconv.Atoi(in.Param("id"))
	if err != nil {
		return server.Fail("invalid id")
	}
	u, err := UserFindById(id)
	if err != nil {
		return server.Fail(err.Error())
	}
	if u == nil {
		return server.Fail("User not found")
	}
	return server.Of(u)
}

// UpdateById updates a record by primary key.
func (s *UserService) UpdateById(in aifei.Input) aifei.Output {
	id, err := strconv.Atoi(in.Param("id"))
	if err != nil {
		return server.Fail("invalid id")
	}
	existing, err := UserFindById(id)
	if err != nil || existing == nil {
		return server.Fail("User not found")
	}
	if err := in.GetBean(existing); err != nil {
		return server.Fail("invalid request: " + err.Error())
	}
	if _, err := existing.Update(); err != nil {
		return server.Fail(err.Error())
	}
	return server.Of(id)
}

// DeleteById deletes a record by primary key.
func (s *UserService) DeleteById(in aifei.Input) aifei.Output {
	id, err := strconv.Atoi(in.Param("id"))
	if err != nil {
		return server.Fail("invalid id")
	}
	if _, err := UserDeleteById(id); err != nil {
		return server.Fail(err.Error())
	}
	return server.Of(nil)
}
