// Generated by Aifei Generator. DO NOT EDIT.

package internal

import (
	_ "github.com/crazy-airhead/aifei-go/_test/demo/internal/loginlog"
	_ "github.com/crazy-airhead/aifei-go/_test/demo/internal/user"
)

// Tables are registered via init() functions in each per-table package.
// Use db.Tables() to retrieve all registered tables.
