package damigen

// clientTemplate renders the code-generated consumer stubs using the Enjoy
// template engine — the same engine as tools/generator, for a unified codegen
// story. It produces one XxxClient per //dami:provider interface, each
// implementing the interface and delegating to dami.Call1/Call0.
//
// Enjoy syntax: #(expr) outputs an expression; #for (x : list) ... #end loops;
// struct fields are reached via dot access (e.g. #(iface.Name)).
const clientTemplate = `// Code generated by dami-gen; DO NOT EDIT.

package #(Package)

import (
	"context"

	"#(ImportPath)"
)
#for (iface : Ifaces)
// #(iface.Name)Client is the code-generated consumer for the #(iface.Name) provider
// (topic mapping "#(iface.Topic)"). It implements #(iface.Name).
type #(iface.Name)Client struct {
	Bus *dami.Bus
}

// New#(iface.Name)Client builds a #(iface.Name)Client over bus.
func New#(iface.Name)Client(bus *dami.Bus) *#(iface.Name)Client {
	return &#(iface.Name)Client{Bus: bus}
}
#for (m : iface.Methods)
func (c *#(iface.Name)Client) #(m.Name)#(m.Params) #(m.Results) {
	#(m.CallExpr)
}
#end

#end
`
