// Generated by Aifei Generator. DO NOT EDIT.

package flow

import (
	"github.com/crazy-airhead/aifei-go/db"
	"reflect"
	"time"
)

var TableFlowTask = &db.Table{
	Name:             "sys_flow_task",
	Fields:           "id,title,user_id,state,created_at",
	PrimaryKeys:      []string{"id"},
	GeneratedColumns: []string{},
	FieldTypes: map[string]reflect.Type{
		"id":         reflect.TypeOf(int(0)),
		"title":      reflect.TypeOf(""),
		"user_id":    reflect.TypeOf(int(0)),
		"state":      reflect.TypeOf(""),
		"created_at": reflect.TypeOf(time.Time{}),
	},
}

type BaseFlowTask struct {
	*db.Row
}

func NewBaseFlowTask() *BaseFlowTask {
	return &BaseFlowTask{Row: db.NewRow(TableFlowTask.Name)}
}

// NewFlowTaskWithRow wraps a queried *db.Row as a BaseFlowTask. Unlike a bare
// struct literal it runs initFlowTaskRow, so the result carries table name,
// primary keys and decoded JSON columns — Update()/Delete() work on it.
func NewFlowTaskWithRow(row *db.Row) *BaseFlowTask {
	return &BaseFlowTask{Row: initFlowTaskRow(row)}
}

func (r *BaseFlowTask) Id() int {
	return r.GetInt("id")
}

func (r *BaseFlowTask) Title() string {
	return r.GetStr("title")
}

func (r *BaseFlowTask) UserId() int {
	return r.GetInt("user_id")
}

func (r *BaseFlowTask) State() string {
	return r.GetStr("state")
}

func (r *BaseFlowTask) CreatedAt() time.Time {
	return r.GetTime("created_at")
}

func (r *BaseFlowTask) SetId(v int) *BaseFlowTask {
	r.Set("id", v)
	return r
}

func (r *BaseFlowTask) SetTitle(v string) *BaseFlowTask {
	r.Set("title", v)
	return r
}

func (r *BaseFlowTask) SetUserId(v int) *BaseFlowTask {
	r.Set("user_id", v)
	return r
}

func (r *BaseFlowTask) SetState(v string) *BaseFlowTask {
	r.Set("state", v)
	return r
}

func (r *BaseFlowTask) SetCreatedAt(v time.Time) *BaseFlowTask {
	r.Set("created_at", v)
	return r
}

func (r *BaseFlowTask) Id_(v int) *BaseFlowTask {
	return r.SetId(v)
}

func (r *BaseFlowTask) Title_(v string) *BaseFlowTask {
	return r.SetTitle(v)
}

func (r *BaseFlowTask) UserId_(v int) *BaseFlowTask {
	return r.SetUserId(v)
}

func (r *BaseFlowTask) State_(v string) *BaseFlowTask {
	return r.SetState(v)
}

func (r *BaseFlowTask) CreatedAt_(v time.Time) *BaseFlowTask {
	return r.SetCreatedAt(v)
}

func (r *BaseFlowTask) Insert() (*BaseFlowTask, error) {
	_, err := r.Row.Insert()
	return r, err
}

func (r *BaseFlowTask) Update() (bool, error) {
	return r.Row.Update()
}

func (r *BaseFlowTask) Delete() (bool, error) {
	return r.Row.Delete()
}

func initFlowTaskRow(row *db.Row) *db.Row {
	return db.DecodeJSONFields(row.SetTable(TableFlowTask.Name).SetPrimaryKeys(TableFlowTask.PrimaryKeys...))
}

// FlowTaskFromRow wraps a raw-SQL *db.Row as a typed *FlowTask (nil-safe).
// It lives in base.go — which re-generation always overwrites — so existing
// projects pick it up by re-running the generator; referencing the model type
// from here is fine within one package.
func FlowTaskFromRow(row *db.Row) *FlowTask {
	if row == nil {
		return nil
	}
	return &FlowTask{BaseFlowTask: NewFlowTaskWithRow(row)}
}

// FlowTaskFromRows wraps a slice of raw-SQL rows as typed *FlowTask values.
func FlowTaskFromRows(rows []*db.Row) []*FlowTask {
	out := make([]*FlowTask, len(rows))
	for i, row := range rows {
		out[i] = FlowTaskFromRow(row)
	}
	return out
}

func (b *BaseFlowTask) InitRow(row *db.Row) {
	b.Row = initFlowTaskRow(row)
}

func init() {
	db.RegisterTable(TableFlowTask)
}
