// Generated by Aifei Generator. DO NOT EDIT.

package flow

import (
	"github.com/crazy-airhead/aifei-go/db"
	"reflect"
	"time"
)

var TableFlowLog = &db.Table{
	Name:             "sys_flow_log",
	Fields:           "id,task_id,user_id,action,created_at",
	PrimaryKeys:      []string{"id"},
	GeneratedColumns: []string{},
	FieldTypes: map[string]reflect.Type{
		"id":         reflect.TypeOf(int(0)),
		"task_id":    reflect.TypeOf(int(0)),
		"user_id":    reflect.TypeOf(int(0)),
		"action":     reflect.TypeOf(""),
		"created_at": reflect.TypeOf(time.Time{}),
	},
}

type BaseFlowLog struct {
	*db.Row
}

func NewBaseFlowLog() *BaseFlowLog {
	return &BaseFlowLog{Row: db.NewRow(TableFlowLog.Name)}
}

// NewFlowLogWithRow wraps a queried *db.Row as a BaseFlowLog. Unlike a bare
// struct literal it runs initFlowLogRow, so the result carries table name,
// primary keys and decoded JSON columns — Update()/Delete() work on it.
func NewFlowLogWithRow(row *db.Row) *BaseFlowLog {
	return &BaseFlowLog{Row: initFlowLogRow(row)}
}

func (r *BaseFlowLog) Id() int {
	return r.GetInt("id")
}

func (r *BaseFlowLog) TaskId() int {
	return r.GetInt("task_id")
}

func (r *BaseFlowLog) UserId() int {
	return r.GetInt("user_id")
}

func (r *BaseFlowLog) Action() string {
	return r.GetStr("action")
}

func (r *BaseFlowLog) CreatedAt() time.Time {
	return r.GetTime("created_at")
}

func (r *BaseFlowLog) SetId(v int) *BaseFlowLog {
	r.Set("id", v)
	return r
}

func (r *BaseFlowLog) SetTaskId(v int) *BaseFlowLog {
	r.Set("task_id", v)
	return r
}

func (r *BaseFlowLog) SetUserId(v int) *BaseFlowLog {
	r.Set("user_id", v)
	return r
}

func (r *BaseFlowLog) SetAction(v string) *BaseFlowLog {
	r.Set("action", v)
	return r
}

func (r *BaseFlowLog) SetCreatedAt(v time.Time) *BaseFlowLog {
	r.Set("created_at", v)
	return r
}

func (r *BaseFlowLog) Id_(v int) *BaseFlowLog {
	return r.SetId(v)
}

func (r *BaseFlowLog) TaskId_(v int) *BaseFlowLog {
	return r.SetTaskId(v)
}

func (r *BaseFlowLog) UserId_(v int) *BaseFlowLog {
	return r.SetUserId(v)
}

func (r *BaseFlowLog) Action_(v string) *BaseFlowLog {
	return r.SetAction(v)
}

func (r *BaseFlowLog) CreatedAt_(v time.Time) *BaseFlowLog {
	return r.SetCreatedAt(v)
}

func (r *BaseFlowLog) Insert() (*BaseFlowLog, error) {
	_, err := r.Row.Insert()
	return r, err
}

func (r *BaseFlowLog) Update() (bool, error) {
	return r.Row.Update()
}

func (r *BaseFlowLog) Delete() (bool, error) {
	return r.Row.Delete()
}

func initFlowLogRow(row *db.Row) *db.Row {
	return db.DecodeJSONFields(row.SetTable(TableFlowLog.Name).SetPrimaryKeys(TableFlowLog.PrimaryKeys...))
}

// FlowLogFromRow wraps a raw-SQL *db.Row as a typed *FlowLog (nil-safe).
// It lives in base.go — which re-generation always overwrites — so existing
// projects pick it up by re-running the generator; referencing the model type
// from here is fine within one package.
func FlowLogFromRow(row *db.Row) *FlowLog {
	if row == nil {
		return nil
	}
	return &FlowLog{BaseFlowLog: NewFlowLogWithRow(row)}
}

// FlowLogFromRows wraps a slice of raw-SQL rows as typed *FlowLog values.
func FlowLogFromRows(rows []*db.Row) []*FlowLog {
	out := make([]*FlowLog, len(rows))
	for i, row := range rows {
		out[i] = FlowLogFromRow(row)
	}
	return out
}

func init() {
	db.RegisterTable(TableFlowLog)
}
