// Generated by Aifei Generator.
// This file is NOT overwritten on re-generation. Add custom queries here.

package flow

import (
	"github.com/crazy-airhead/aifei-go/db"
)

// FlowLogDao is a typed query builder for FlowLog (table "sys_flow_log").
// Chain a Sql/Select/RawSql setup method (they return *FlowLogDao), then call a
// terminal method (Find/FindFirst/Paginate/Count/...) which returns typed
// results. The table is already bound, so unlike db.Dao no table name is
// passed on every call. Create a fresh one per query via NewFlowLogDao().
type FlowLogDao struct {
	*db.Dao
}

// NewFlowLogDao returns a fresh typed Dao bound to the default db config.
func NewFlowLogDao() *FlowLogDao {
	return &FlowLogDao{Dao: db.Use()}
}

// Sql sets an Enjoy SQL template and its named parameters.
func (d *FlowLogDao) Sql(sqlStr string, data map[string]interface{}) *FlowLogDao {
	d.Dao.Sql(sqlStr, data)
	return d
}

// SqlWithArgs sets an Enjoy SQL template with positional arguments.
func (d *FlowLogDao) SqlWithArgs(sqlStr string, args ...interface{}) *FlowLogDao {
	d.Dao.SqlWithArgs(sqlStr, args...)
	return d
}

// SqlById sets a cached Enjoy SQL template (by id) and its named parameters.
func (d *FlowLogDao) SqlById(sqlID string, data map[string]interface{}) *FlowLogDao {
	d.Dao.SqlById(sqlID, data)
	return d
}

// SqlByIdWithArgs sets a cached Enjoy SQL template (by id) with positional arguments.
func (d *FlowLogDao) SqlByIdWithArgs(sqlID string, args ...interface{}) *FlowLogDao {
	d.Dao.SqlByIdWithArgs(sqlID, args...)
	return d
}

// RawSql sets a raw SQL string with positional arguments.
func (d *FlowLogDao) RawSql(query string, args ...interface{}) *FlowLogDao {
	d.Dao.RawSql(query, args...)
	return d
}

// Select restricts the selected columns.
func (d *FlowLogDao) Select(fields string) *FlowLogDao {
	d.Dao.Select(fields)
	return d
}

// Find executes the query and returns all matching rows as typed models.
func (d *FlowLogDao) Find() ([]*FlowLog, error) {
	rows, err := d.Dao.Find()
	if err != nil {
		return nil, err
	}
	return FlowLogFromRows(rows), nil
}

// FindFirst executes the query and returns the first matching row as a typed model.
func (d *FlowLogDao) FindFirst() (*FlowLog, error) {
	row, err := d.Dao.FindFirst()
	if err != nil {
		return nil, err
	}
	return FlowLogFromRow(row), nil
}

// FindOne executes the query and returns the single matching row as a typed model.
func (d *FlowLogDao) FindOne() (*FlowLog, error) {
	row, err := d.Dao.FindOne()
	if err != nil {
		return nil, err
	}
	return FlowLogFromRow(row), nil
}

// FindExists reports whether the query matches any row.
func (d *FlowLogDao) FindExists() (bool, error) {
	return d.Dao.FindExists()
}

// FlowLogPage is db.Page with typed rows: the wire format (json tags) is
// identical, but Rows carries *FlowLog instead of *db.Row.
type FlowLogPage struct {
	PageNum    int        `json:"pageNum"`
	PageSize   int        `json:"pageSize"`
	TotalRows  int64      `json:"totalRows"`
	TotalPages int        `json:"totalPages"`
	Rows       []*FlowLog `json:"rows"`
}

// Paginate executes the query and returns a page of typed rows.
func (d *FlowLogDao) Paginate(pageNum, pageSize int) (*FlowLogPage, error) {
	page, err := d.Dao.Paginate(pageNum, pageSize)
	if err != nil {
		return nil, err
	}
	return &FlowLogPage{
		PageNum:    page.PageNum,
		PageSize:   page.PageSize,
		TotalRows:  page.TotalRows,
		TotalPages: page.TotalPages,
		Rows:       FlowLogFromRows(page.Rows),
	}, nil
}

// FindBy queries by a where clause or a single field with arguments.
func (d *FlowLogDao) FindBy(whereOrField string, args ...interface{}) ([]*FlowLog, error) {
	rows, err := d.Dao.FindBy(TableFlowLog.Name, whereOrField, args...)
	if err != nil {
		return nil, err
	}
	return FlowLogFromRows(rows), nil
}

// FindFirstBy queries the first row by a where clause or a single field with arguments.
func (d *FlowLogDao) FindFirstBy(whereOrField string, args ...interface{}) (*FlowLog, error) {
	row, err := d.Dao.FindFirstBy(TableFlowLog.Name, whereOrField, args...)
	if err != nil {
		return nil, err
	}
	return FlowLogFromRow(row), nil
}

// FindIn loads rows where field matches any of values (a typed IN query),
// e.g. FindIn("user_id", 1, 2, 3).
func (d *FlowLogDao) FindIn(field string, values ...interface{}) ([]*FlowLog, error) {
	rows, err := d.Dao.FindIn(TableFlowLog.Name, field, values...)
	if err != nil {
		return nil, err
	}
	return FlowLogFromRows(rows), nil
}

// FindByID loads a single row by its primary key.
func (d *FlowLogDao) FindByID(id int) (*FlowLog, error) {
	row, err := d.Dao.FindByID(TableFlowLog.Name, id)
	if err != nil {
		return nil, err
	}
	return FlowLogFromRow(row), nil
}

// DeleteByID deletes a single row by its primary key.
func (d *FlowLogDao) DeleteByID(id int) (bool, error) {
	return d.Dao.DeleteByID(TableFlowLog.Name, id)
}

// FindByIds loads rows matching any of the given primary keys (WHERE pk IN ...).
func (d *FlowLogDao) FindByIds(ids ...int) ([]*FlowLog, error) {
	vals := make([]interface{}, len(ids))
	for i, id := range ids {
		vals[i] = id
	}
	rows, err := d.Dao.FindIn(TableFlowLog.Name, "id", vals...)
	if err != nil {
		return nil, err
	}
	return FlowLogFromRows(rows), nil
}

// DeleteByIds deletes rows matching any of the given primary keys (WHERE pk IN ...).
func (d *FlowLogDao) DeleteByIds(ids ...int) (int64, error) {
	vals := make([]interface{}, len(ids))
	for i, id := range ids {
		vals[i] = id
	}
	return d.Dao.DeleteInIds(TableFlowLog.Name, vals...)
}

// Count returns the total number of rows.
func (d *FlowLogDao) Count() (int64, error) {
	return d.Dao.Count(TableFlowLog.Name)
}

// CountBy counts rows matching a where clause or a single field with arguments.
func (d *FlowLogDao) CountBy(whereOrField string, args ...interface{}) (int64, error) {
	return d.Dao.CountBy(TableFlowLog.Name, whereOrField, args...)
}

// DeleteBy deletes rows matching a where clause or a single field with arguments.
func (d *FlowLogDao) DeleteBy(whereOrField string, args ...interface{}) (int64, error) {
	return d.Dao.DeleteBy(TableFlowLog.Name, whereOrField, args...)
}

// FlowLogFindById loads a single row by its primary key.
func FlowLogFindById(id int) (*FlowLog, error) {
	return NewFlowLogDao().FindByID(id)
}

// FlowLogDeleteById deletes a single row by its primary key.
func FlowLogDeleteById(id int) (bool, error) {
	return NewFlowLogDao().DeleteByID(id)
}

// FlowLogFindByIds loads rows matching any of the given primary keys.
func FlowLogFindByIds(ids ...int) ([]*FlowLog, error) {
	return NewFlowLogDao().FindByIds(ids...)
}

// FlowLogDeleteByIds deletes rows matching any of the given primary keys.
func FlowLogDeleteByIds(ids ...int) (int64, error) {
	return NewFlowLogDao().DeleteByIds(ids...)
}

// FlowLogFindBy queries by a where clause or a single field with arguments.
func FlowLogFindBy(whereOrField string, args ...interface{}) ([]*FlowLog, error) {
	return NewFlowLogDao().FindBy(whereOrField, args...)
}

// FlowLogFindFirstBy queries the first row by a where clause or a single field with arguments.
func FlowLogFindFirstBy(whereOrField string, args ...interface{}) (*FlowLog, error) {
	return NewFlowLogDao().FindFirstBy(whereOrField, args...)
}

// FlowLogDeleteBy deletes rows matching a where clause or a single field with arguments.
func FlowLogDeleteBy(whereOrField string, args ...interface{}) (int64, error) {
	return NewFlowLogDao().DeleteBy(whereOrField, args...)
}

// FlowLogCount returns the total number of rows.
func FlowLogCount() (int64, error) {
	return NewFlowLogDao().Count()
}

// FlowLogCountBy counts rows matching a where clause or a single field with arguments.
func FlowLogCountBy(whereOrField string, args ...interface{}) (int64, error) {
	return NewFlowLogDao().CountBy(whereOrField, args...)
}
