// Generated by Aifei Generator.
// This file is NOT overwritten on re-generation. Add custom queries here.

package flow

import (
	"github.com/crazy-airhead/aifei-go/db"
)

// FlowTaskDao is a typed query builder for FlowTask (table "sys_flow_task").
// Chain a Sql/Select/RawSql setup method (they return *FlowTaskDao), then call a
// terminal method (Find/FindFirst/Paginate/Count/...) which returns typed
// results. The table is already bound, so unlike db.Dao no table name is
// passed on every call. Create a fresh one per query via NewFlowTaskDao().
type FlowTaskDao struct {
	*db.Dao
}

// NewFlowTaskDao returns a fresh typed Dao bound to the default db config.
func NewFlowTaskDao() *FlowTaskDao {
	return &FlowTaskDao{Dao: db.Use()}
}

// Sql sets an Enjoy SQL template and its named parameters.
func (d *FlowTaskDao) Sql(sqlStr string, data map[string]interface{}) *FlowTaskDao {
	d.Dao.Sql(sqlStr, data)
	return d
}

// SqlWithArgs sets an Enjoy SQL template with positional arguments.
func (d *FlowTaskDao) SqlWithArgs(sqlStr string, args ...interface{}) *FlowTaskDao {
	d.Dao.SqlWithArgs(sqlStr, args...)
	return d
}

// SqlById sets a cached Enjoy SQL template (by id) and its named parameters.
func (d *FlowTaskDao) SqlById(sqlID string, data map[string]interface{}) *FlowTaskDao {
	d.Dao.SqlById(sqlID, data)
	return d
}

// SqlByIdWithArgs sets a cached Enjoy SQL template (by id) with positional arguments.
func (d *FlowTaskDao) SqlByIdWithArgs(sqlID string, args ...interface{}) *FlowTaskDao {
	d.Dao.SqlByIdWithArgs(sqlID, args...)
	return d
}

// RawSql sets a raw SQL string with positional arguments.
func (d *FlowTaskDao) RawSql(query string, args ...interface{}) *FlowTaskDao {
	d.Dao.RawSql(query, args...)
	return d
}

// Select restricts the selected columns.
func (d *FlowTaskDao) Select(fields string) *FlowTaskDao {
	d.Dao.Select(fields)
	return d
}

// Find executes the query and returns all matching rows as typed models.
func (d *FlowTaskDao) Find() ([]*FlowTask, error) {
	return d.Dao.FindAs[FlowTask]()
}

// FindFirst executes the query and returns the first matching row as a typed model.
func (d *FlowTaskDao) FindFirst() (*FlowTask, error) {
	return d.Dao.FindFirstAs[FlowTask]()
}

// FindOne executes the query and returns the single matching row as a typed model.
func (d *FlowTaskDao) FindOne() (*FlowTask, error) {
	return d.Dao.FindOneAs[FlowTask]()
}

// FindExists reports whether the query matches any row.
func (d *FlowTaskDao) FindExists() (bool, error) {
	return d.Dao.FindExists()
}

// FlowTaskPage is db.PageAs with typed rows: the wire format (json tags) is
// identical to db.Page, but Rows carries *FlowTask instead of *db.Row.
type FlowTaskPage = db.PageAs[*FlowTask]

// Paginate executes the query and returns a page of typed rows.
func (d *FlowTaskDao) Paginate(pageNum, pageSize int) (*FlowTaskPage, error) {
	return d.Dao.PaginateAs[FlowTask](pageNum, pageSize)
}

// FindBy queries by a where clause or a single field with arguments.
func (d *FlowTaskDao) FindBy(whereOrField string, args ...interface{}) ([]*FlowTask, error) {
	return d.Dao.FindByAs[FlowTask](TableFlowTask.Name, whereOrField, args...)
}

// FindFirstBy queries the first row by a where clause or a single field with arguments.
func (d *FlowTaskDao) FindFirstBy(whereOrField string, args ...interface{}) (*FlowTask, error) {
	return d.Dao.FindFirstByAs[FlowTask](TableFlowTask.Name, whereOrField, args...)
}

// FindIn loads rows where field matches any of values (a typed IN query),
// e.g. FindIn("user_id", 1, 2, 3).
func (d *FlowTaskDao) FindIn(field string, values ...interface{}) ([]*FlowTask, error) {
	rows, err := d.Dao.FindIn(TableFlowTask.Name, field, values...)
	if err != nil {
		return nil, err
	}
	return FlowTaskFromRows(rows), nil
}

// FindByID loads a single row by its primary key.
func (d *FlowTaskDao) FindByID(id int) (*FlowTask, error) {
	return d.Dao.FindByIDAs[FlowTask](TableFlowTask.Name, id)
}

// DeleteByID deletes a single row by its primary key.
func (d *FlowTaskDao) DeleteByID(id int) (bool, error) {
	return d.Dao.DeleteByID(TableFlowTask.Name, id)
}

// FindByIds loads rows matching any of the given primary keys (WHERE pk IN ...).
func (d *FlowTaskDao) FindByIds(ids ...int) ([]*FlowTask, error) {
	vals := make([]interface{}, len(ids))
	for i, id := range ids {
		vals[i] = id
	}
	rows, err := d.Dao.FindIn(TableFlowTask.Name, "id", vals...)
	if err != nil {
		return nil, err
	}
	return FlowTaskFromRows(rows), nil
}

// DeleteByIds deletes rows matching any of the given primary keys (WHERE pk IN ...).
func (d *FlowTaskDao) DeleteByIds(ids ...int) (int64, error) {
	vals := make([]interface{}, len(ids))
	for i, id := range ids {
		vals[i] = id
	}
	return d.Dao.DeleteInIds(TableFlowTask.Name, vals...)
}

// Count returns the total number of rows.
func (d *FlowTaskDao) Count() (int64, error) {
	return d.Dao.Count(TableFlowTask.Name)
}

// CountBy counts rows matching a where clause or a single field with arguments.
func (d *FlowTaskDao) CountBy(whereOrField string, args ...interface{}) (int64, error) {
	return d.Dao.CountBy(TableFlowTask.Name, whereOrField, args...)
}

// DeleteBy deletes rows matching a where clause or a single field with arguments.
func (d *FlowTaskDao) DeleteBy(whereOrField string, args ...interface{}) (int64, error) {
	return d.Dao.DeleteBy(TableFlowTask.Name, whereOrField, args...)
}

// FlowTaskFindById loads a single row by its primary key.
func FlowTaskFindById(id int) (*FlowTask, error) {
	return NewFlowTaskDao().FindByID(id)
}

// FlowTaskDeleteById deletes a single row by its primary key.
func FlowTaskDeleteById(id int) (bool, error) {
	return NewFlowTaskDao().DeleteByID(id)
}

// FlowTaskFindByIds loads rows matching any of the given primary keys.
func FlowTaskFindByIds(ids ...int) ([]*FlowTask, error) {
	return NewFlowTaskDao().FindByIds(ids...)
}

// FlowTaskDeleteByIds deletes rows matching any of the given primary keys.
func FlowTaskDeleteByIds(ids ...int) (int64, error) {
	return NewFlowTaskDao().DeleteByIds(ids...)
}

// FlowTaskFindBy queries by a where clause or a single field with arguments.
func FlowTaskFindBy(whereOrField string, args ...interface{}) ([]*FlowTask, error) {
	return NewFlowTaskDao().FindBy(whereOrField, args...)
}

// FlowTaskFindFirstBy queries the first row by a where clause or a single field with arguments.
func FlowTaskFindFirstBy(whereOrField string, args ...interface{}) (*FlowTask, error) {
	return NewFlowTaskDao().FindFirstBy(whereOrField, args...)
}

// FlowTaskDeleteBy deletes rows matching a where clause or a single field with arguments.
func FlowTaskDeleteBy(whereOrField string, args ...interface{}) (int64, error) {
	return NewFlowTaskDao().DeleteBy(whereOrField, args...)
}

// FlowTaskCount returns the total number of rows.
func FlowTaskCount() (int64, error) {
	return NewFlowTaskDao().Count()
}

// FlowTaskCountBy counts rows matching a where clause or a single field with arguments.
func FlowTaskCountBy(whereOrField string, args ...interface{}) (int64, error) {
	return NewFlowTaskDao().CountBy(whereOrField, args...)
}
