// Generated by Aifei Generator.
// This file is NOT overwritten on re-generation. Add custom logic here.

package flow

// FlowLog is the data model for the sys_flow_log table.
type FlowLog struct {
	*BaseFlowLog
}

// NewFlowLog creates a new FlowLog ready for use with GetBean and Insert.
func NewFlowLog() *FlowLog {
	return &FlowLog{BaseFlowLog: NewBaseFlowLog()}
}
