// Generated by Aifei Generator.
// This file is NOT overwritten on re-generation. Add custom logic here.

package flow

// FlowTask is the data model for the sys_flow_task table.
type FlowTask struct {
	*BaseFlowTask
}

// NewFlowTask creates a new FlowTask ready for use with GetBean and Insert.
func NewFlowTask() *FlowTask {
	return &FlowTask{BaseFlowTask: NewBaseFlowTask()}
}
