// Generated by Aifei Generator.
// This file is NOT overwritten on re-generation. Add custom queries here.

package flow

import (
	"github.com/crazy-airhead/aifei-go/aifei"
	"github.com/crazy-airhead/aifei-go/server"
	"strconv"
)

const (
	FlowLogServicePrefix = "/flowLog"

	// flowLogListSql is the Enjoy SQL template for List and Paginate.
	// Query params are matched via the where/and directives in queryConditions.
	flowLogListSql = `SELECT * FROM sys_flow_log
#where(task_id, '=', task_id)
#and(user_id, '=', user_id)
#and(action, '=', action)
#and(created_at, '=', created_at)
ORDER BY id DESC`
)

func init() {
	server.RegisterService(FlowLogServicePrefix, &FlowLogService{})
}

type FlowLogService struct{}

// List returns records matching query params (no pagination).
func (s *FlowLogService) List(in aifei.Input) aifei.Output {
	filter := in.GetMap()
	rows, err := NewFlowLogDao().Sql(flowLogListSql, filter).Find()
	if err != nil {
		return server.Fail(err.Error())
	}
	return server.Of(rows)
}

// Paginate returns paginated records matching query params.
func (s *FlowLogService) Paginate(in aifei.Input) aifei.Output {
	pageNum := in.GetInt("page", 1)
	pageSize := in.GetInt("size", 10)
	filter := in.GetMap()
	page, err := NewFlowLogDao().Sql(flowLogListSql, filter).Paginate(pageNum, pageSize)
	if err != nil {
		return server.Fail(err.Error())
	}
	return server.Of(page)
}

// Create inserts a new record.
func (s *FlowLogService) Create(in aifei.Input) aifei.Output {
	u := NewFlowLog()
	if err := in.GetBean(u); err != nil {
		return server.Fail("invalid request: " + err.Error())
	}
	result, err := u.Insert()
	if err != nil {
		return server.Fail(err.Error())
	}
	return server.Of(result.GetID())
}

// GetById retrieves a record by primary key.
func (s *FlowLogService) GetById(in aifei.Input) aifei.Output {
	id, err := strconv.Atoi(in.Param("id"))
	if err != nil {
		return server.Fail("invalid id")
	}
	u, err := FlowLogFindById(id)
	if err != nil {
		return server.Fail(err.Error())
	}
	if u == nil {
		return server.Fail("FlowLog not found")
	}
	return server.Of(u)
}

// UpdateById updates a record by primary key.
func (s *FlowLogService) UpdateById(in aifei.Input) aifei.Output {
	id, err := strconv.Atoi(in.Param("id"))
	if err != nil {
		return server.Fail("invalid id")
	}
	existing, err := FlowLogFindById(id)
	if err != nil || existing == nil {
		return server.Fail("FlowLog not found")
	}
	if err := in.GetBean(existing); err != nil {
		return server.Fail("invalid request: " + err.Error())
	}
	if _, err := existing.Update(); err != nil {
		return server.Fail(err.Error())
	}
	return server.Of(id)
}

// DeleteById deletes a record by primary key.
func (s *FlowLogService) DeleteById(in aifei.Input) aifei.Output {
	id, err := strconv.Atoi(in.Param("id"))
	if err != nil {
		return server.Fail("invalid id")
	}
	if _, err := FlowLogDeleteById(id); err != nil {
		return server.Fail(err.Error())
	}
	return server.Of(nil)
}
