// Generated by Aifei Generator.
// This file is NOT overwritten on re-generation. Add custom queries here.

package flow

import (
	"strconv"

	"github.com/crazy-airhead/aifei-go/_test/demo/internal/user"
	"github.com/crazy-airhead/aifei-go/aifei"
	"github.com/crazy-airhead/aifei-go/server"
)

const (
	FlowTaskServicePrefix = "/flowTask"

	// flowTaskListSql is the Enjoy SQL template for List and Paginate.
	// Query params are matched via the where/and directives in queryConditions.
	flowTaskListSql = `SELECT * FROM sys_flow_task
#where(title, '=', title)
#and(user_id, '=', user_id)
#and(state, '=', state)
#and(created_at, '=', created_at)
ORDER BY id DESC`
)

func init() {
	server.RegisterService(FlowTaskServicePrefix, &FlowTaskService{})
}

type FlowTaskService struct{}

// List returns records matching query params (no pagination).
func (s *FlowTaskService) List(in aifei.Input) aifei.Output {
	filter := in.GetMap()
	rows, err := NewFlowTaskDao().Sql(flowTaskListSql, filter).Find()
	if err != nil {
		return server.Fail(err.Error())
	}
	return server.Of(rows)
}

// Paginate returns paginated records matching query params.
func (s *FlowTaskService) Paginate(in aifei.Input) aifei.Output {
	pageNum := in.GetInt("page", 1)
	pageSize := in.GetInt("size", 10)
	filter := in.GetMap()
	page, err := NewFlowTaskDao().Sql(flowTaskListSql, filter).Paginate(pageNum, pageSize)
	if err != nil {
		return server.Fail(err.Error())
	}
	return server.Of(page)
}

// Create inserts a new record.
func (s *FlowTaskService) Create(in aifei.Input) aifei.Output {
	u := NewFlowTask()
	if err := in.GetBean(u); err != nil {
		return server.Fail("invalid request: " + err.Error())
	}
	result, err := u.Insert()
	if err != nil {
		return server.Fail(err.Error())
	}
	return server.Of(result.GetID())
}

// GetById retrieves a record by primary key, composed with its owner's name.
//
// 跨包调用示例（「跨包只向下」规则）：flow 领域的 service 组合 user 领域的
// 模型——service → 他包 dao/model 是数据依赖，天然无环，普通 import 即可。
func (s *FlowTaskService) GetById(in aifei.Input) aifei.Output {
	id, err := strconv.Atoi(in.Param("id"))
	if err != nil {
		return server.Fail("invalid id")
	}
	u, err := FlowTaskFindById(id)
	if err != nil {
		return server.Fail(err.Error())
	}
	if u == nil {
		return server.Fail("FlowTask not found")
	}

	// 向下调用 user 包的包级函数拿模型，拼装跨领域的响应视图
	owner, err := user.UserFindById(u.UserId())
	if err != nil {
		return server.Fail(err.Error())
	}
	userName := ""
	if owner != nil {
		userName = owner.Name()
	}
	return server.Of(map[string]interface{}{
		"task":     u,
		"userName": userName,
	})
}

// UpdateById updates a record by primary key.
func (s *FlowTaskService) UpdateById(in aifei.Input) aifei.Output {
	id, err := strconv.Atoi(in.Param("id"))
	if err != nil {
		return server.Fail("invalid id")
	}
	existing, err := FlowTaskFindById(id)
	if err != nil || existing == nil {
		return server.Fail("FlowTask not found")
	}
	if err := in.GetBean(existing); err != nil {
		return server.Fail("invalid request: " + err.Error())
	}
	if _, err := existing.Update(); err != nil {
		return server.Fail(err.Error())
	}
	return server.Of(id)
}

// DeleteById deletes a record by primary key.
func (s *FlowTaskService) DeleteById(in aifei.Input) aifei.Output {
	id, err := strconv.Atoi(in.Param("id"))
	if err != nil {
		return server.Fail("invalid id")
	}
	if _, err := FlowTaskDeleteById(id); err != nil {
		return server.Fail(err.Error())
	}
	return server.Of(nil)
}
