package db

import "reflect"

// Table holds runtime table metadata, generated by the code generator.
type Table struct {
	Name        string
	Fields      string
	PrimaryKeys []string
	FieldTypes  map[string]reflect.Type
}

var tableRegistry []*Table

// RegisterTable registers a table metadata into the global registry.
// Generated base.go files call this in their init() function.
func RegisterTable(t *Table) {
	tableRegistry = append(tableRegistry, t)
}

// Tables returns all registered table metadata.
func Tables() []*Table {
	return tableRegistry
}
