// Generated by Aifei Generator.
// This file is NOT overwritten on re-generation. Add custom queries here.

package loginlog

import (
	"github.com/crazy-airhead/aifei-go/db"
)

type Dao struct {
	*db.Dao
}

func NewDao() *Dao {
	return &Dao{Dao: db.Use()}
}

func FindById(id int) (*LoginLog, error) {
	row, err := db.FindByID(Table.Name, id)
	if err != nil {
		return nil, err
	}
	if row == nil {
		return nil, nil
	}
	return &LoginLog{BaseLoginLog: NewWithRow(initRow(row))}, nil
}

func DeleteById(id int) (bool, error) {
	return db.DeleteByID(Table.Name, id)
}

func FindBy(whereOrField string, args ...interface{}) ([]*LoginLog, error) {
	rows, err := db.FindBy(Table.Name, whereOrField, args...)
	if err != nil {
		return nil, err
	}
	result := make([]*LoginLog, len(rows))
	for i, row := range rows {
		result[i] = &LoginLog{BaseLoginLog: NewWithRow(initRow(row))}
	}
	return result, nil
}

func FindFirstBy(whereOrField string, args ...interface{}) (*LoginLog, error) {
	row, err := db.FindFirstBy(Table.Name, whereOrField, args...)
	if err != nil {
		return nil, err
	}
	if row == nil {
		return nil, nil
	}
	return &LoginLog{BaseLoginLog: NewWithRow(initRow(row))}, nil
}

func DeleteBy(whereOrField string, args ...interface{}) (int64, error) {
	return db.DeleteBy(Table.Name, whereOrField, args...)
}

func Count() (int64, error) {
	return db.Count(Table.Name)
}

func CountBy(whereOrField string, args ...interface{}) (int64, error) {
	return db.CountBy(Table.Name, whereOrField, args...)
}
