// Generated by Aifei Generator.
// This file is NOT overwritten on re-generation. Add custom logic here.

package loginlog

// LoginLog is the data model for the sys_login_log table.
type LoginLog struct {
	*BaseLoginLog
}

// New creates a new LoginLog ready for use with GetBean and Insert.
func New() *LoginLog {
	return &LoginLog{BaseLoginLog: NewBase()}
}
